# Chapter 6 - Other Popular Machine Learning Methods

## Segment 2 - A Neurral network with a Perceptron

In [1]:
import numpy as np 
import pandas as pd 
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
#How to import the Perceptron
from sklearn.linear_model import Perceptron

In [6]:
iris = datasets.load_iris()
X = iris.data 
y = iris.target

X[:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [8]:
standardize = StandardScaler()
standardized_x_test = standardize.fit_transform(X_test)
standardized_x_train= standardize.fit_transform(X_train)

In [10]:
standardized_x_test[0:10,]

array([[ 0.41153542,  0.71793955,  1.17505109,  1.6168359 ],
       [ 0.29615166, -0.61157813,  0.46528869,  0.68404596],
       [-1.78075606,  0.45203601, -1.60485166, -1.44804534],
       [ 0.18076789, -0.07977106,  0.34699495,  0.15102313],
       [ 0.06538413, -2.20699934,  0.58358242,  0.28427884],
       [ 0.87307047,  0.18613247,  0.40614182,  0.28427884],
       [-0.28076715, -0.07977106,  0.11040749, -0.11548828],
       [ 1.21922175,  0.45203601,  0.40614182,  0.15102313],
       [-1.78075606, -0.07977106, -1.60485166, -1.44804534],
       [ 1.44998928,  0.45203601,  1.17505109,  0.68404596]])

In [11]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)
perceptron.fit(standardized_x_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [12]:
y_pred = perceptron.predict(standardized_x_test)

In [13]:
print(y_test)

[2 2 0 1 2 1 1 1 0 2 2 2 0 0 1 1 2 1 0 1 1 0 1 2 2 0 2 0 1 2]


In [14]:
print(y_pred)

[2 1 0 1 1 0 1 0 0 2 2 1 0 0 1 1 2 1 0 1 1 0 0 2 2 0 2 0 1 2]


In [15]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.73      1.00      0.84         8
           1       0.73      0.73      0.73        11
           2       1.00      0.73      0.84        11

    accuracy                           0.80        30
   macro avg       0.82      0.82      0.80        30
weighted avg       0.83      0.80      0.80        30

