In [1]:
2**1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [2]:
import numpy as np

In [3]:
np.int64(2)**1000

0

In [4]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
len(arr)

3

In [6]:
arr[1]

2

In [7]:
type(arr[1])

numpy.int32

In [8]:
arr.dtype

dtype('int32')

In [10]:
arrr = np.array([1,2,3], dtype=np.int64)
arrr


array([1, 2, 3], dtype=int64)

In [11]:
arrr*arr

array([1, 4, 9], dtype=int64)

In [12]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

In [13]:
%time v1 * v2

Wall time: 3.99 ms


array([0.40475628, 0.19428258, 0.10378727, ..., 0.01934454, 0.17754832,
       0.18676949])

In [14]:
np.dot(arr,arr)

14

In [15]:
arr * arr

array([1, 4, 9])

In [16]:
arr + arr

array([2, 4, 6])

In [17]:
arr @ arr
# dot product

14

In [18]:
# Long way to create an array
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# Short way to create an array
v = np.arange(12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
v.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
# Shorter way to create an array
mat = np.arange(12).reshape(4,3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
# To get the shape of an array
mat.shape

(4, 3)

In [28]:
# Reshaping an array
mat2 = mat.reshape(3,4)
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
# Change a value at [row, column]
mat[1,2] = 17
mat

array([[ 0,  1,  2],
       [ 3,  4, 17],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
# Value also changed at mat2
mat2

array([[ 0,  1,  2,  3],
       [ 4, 17,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
# To transpose a matrix
mat.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2, 17,  8, 11]])

## Slicing

In [34]:
# We get the first index, but not the last one.
nums = [1,2,3,4,5]
nums[2:4]

[3, 4]

In [35]:
# Slicing is useful to get a subset of data for testing and training purposes.
v = np.arange(1,6)
v[2:4]

array([3, 4])

In [36]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
# First row
arr[0]

array([0, 1, 2, 3])

In [38]:
# Second row, second column value
arr[1,1]

5

In [39]:
# Al rows, of second column
arr[:, 1]

array([1, 5, 9])

In [40]:
# All rows of second column reshaped into 3 rows and 1 column
arr[:,1].reshape((3,1))

array([[1],
       [5],
       [9]])

In [41]:
arr[1:, 2:]

array([[ 6,  7],
       [10, 11]])

In [43]:
#Broadcasting when we want to normalise parts of an array
arr[1:, 2:] = 69
arr

array([[ 0,  1,  2,  3],
       [ 4,  5, 69, 69],
       [ 8,  9, 69, 69]])