In [1]:
2**1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [2]:
import numpy as np

In [3]:
np.int64(2)**1000

0

In [4]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
len(arr)

3

In [6]:
arr[1]

2

In [7]:
type(arr[1])

numpy.int32

In [8]:
arr.dtype

dtype('int32')

In [9]:
arrr = np.array([1,2,3], dtype=np.int64)
arrr


array([1, 2, 3], dtype=int64)

In [10]:
arrr*arr

array([1, 4, 9], dtype=int64)

In [11]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

In [12]:
%time v1 * v2

Wall time: 5.98 ms


array([0.1403046 , 0.37110041, 0.36311058, ..., 0.0172565 , 0.18728226,
       0.02072545])

In [13]:
np.dot(arr,arr)

14

In [14]:
arr * arr

array([1, 4, 9])

In [15]:
arr + arr

array([2, 4, 6])

In [16]:
arr @ arr
# dot product

14

In [17]:
# Long way to create an array
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# Short way to create an array
v = np.arange(12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
v.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
# Shorter way to create an array
mat = np.arange(12).reshape(4,3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
# To get the shape of an array
mat.shape

(4, 3)

In [22]:
# Reshaping an array
mat2 = mat.reshape(3,4)
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
# Change a value at [row, column]
mat[1,2] = 17
mat

array([[ 0,  1,  2],
       [ 3,  4, 17],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
# Value also changed at mat2
mat2

array([[ 0,  1,  2,  3],
       [ 4, 17,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
# To transpose a matrix
mat.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2, 17,  8, 11]])

## Slicing

In [26]:
# We get the first index, but not the last one.
nums = [1,2,3,4,5]
nums[2:4]

[3, 4]

In [27]:
# Slicing is useful to get a subset of data for testing and training purposes.
v = np.arange(1,6)
v[2:4]

array([3, 4])

In [28]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
# First row
arr[0]

array([0, 1, 2, 3])

In [30]:
# Second row, second column value
arr[1,1]

5

In [31]:
# Al rows, of second column
arr[:, 1]

array([1, 5, 9])

In [32]:
# All rows of second column reshaped into 3 rows and 1 column
arr[:,1].reshape((3,1))

array([[1],
       [5],
       [9]])

In [33]:
arr[1:, 2:]

array([[ 6,  7],
       [10, 11]])

In [34]:
#Broadcasting when we want to normalise parts of an array
arr[1:, 2:] = 69
arr

array([[ 0,  1,  2,  3],
       [ 4,  5, 69, 69],
       [ 8,  9, 69, 69]])

In [35]:
#Boolean indexing

arr = np.arange(3)

In [36]:
arr

array([0, 1, 2])

In [40]:
arr[np.array([True, True, False])]

array([0, 1])

In [41]:
arr >=1

array([False,  True,  True])

In [42]:
arr[arr>=1]

array([1, 2])

In [43]:
arr = np.arange(10)

In [44]:
arr[(arr>2)&(arr<7)]

array([3, 4, 5, 6])

In [45]:
arr[(arr>7)| (arr<2)]

array([0, 1, 8, 9])

In [46]:
arr[~(arr>7)]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
mat = np.random.rand(5,5)

In [48]:
mat

array([[0.89105155, 0.40856029, 0.69094876, 0.59962624, 0.60766834],
       [0.56895755, 0.53099334, 0.31347149, 0.88811499, 0.86501515],
       [0.94190071, 0.02236723, 0.18532197, 0.04962826, 0.89488801],
       [0.54194877, 0.368877  , 0.41276606, 0.09844566, 0.72515982],
       [0.45005398, 0.46630613, 0.98359734, 0.51750924, 0.34262127]])

In [49]:
mat[np.abs(mat-mat.mean()) > 1.5*mat.std()]

array([0.02236723, 0.04962826, 0.09844566, 0.98359734])

In [53]:
np.abs(mat-mat.mean()) > 1.5*mat.std()

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False,  True, False],
       [False, False, False,  True, False],
       [False, False,  True, False, False]])

In [54]:
mat[np.abs(mat-mat.mean()) > 1.5*mat.std()] = mat.mean()

In [56]:
arr = np.arange(3)
arr + 4

array([4, 5, 6])

In [57]:
matrix = np.arange(9).reshape((3,3))
vec = np.arange(3)

In [58]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
vec

array([0, 1, 2])

In [61]:
matrix + vec

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [62]:
v1 = np.arange(3)
v2 = np.arange(3).reshape(3,1)
v2

array([[0],
       [1],
       [2]])

In [63]:
v1+v2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [64]:
v1*v2

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [65]:
v = np.arange(12).reshape((4,3))

In [66]:
dir(v)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [67]:
v.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [68]:
v.any()

True

In [69]:
v.all()

False

In [70]:
v.argmax()

11

In [77]:
v.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
v.view()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [79]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [80]:
v.prod()

0

In [81]:
v.mean()

5.5

In [84]:
#sum of each row.
v.sum(axis=1)

array([ 3, 12, 21, 30])

In [85]:
#sum of each column
v.sum(axis=0)

array([18, 22, 26])

In [86]:
v1 = v.copy()

In [87]:
v1[0,0] = 1000

In [88]:
v1

array([[1000,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       [   9,   10,   11]])

In [89]:
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [90]:
data = v.dumps()

data

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04K\x03\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i4q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X0\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00\n\x00\x00\x00\x0b\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [96]:

v2 = np.loads(data)
v2

<ipython-input-96-b770a7d8cac2>:1: DeprecationWarning: np.loads is deprecated, use pickle.loads instead
  v2 = np.loads(data)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [97]:
np.prod(v)

0

In [98]:
np.sin(np.pi/2)

1.0

In [99]:
v = np.arange(-3,3)
np.sin(v)

array([-0.14112001, -0.90929743, -0.84147098,  0.        ,  0.84147098,
        0.90929743])

In [100]:
def noneg(n):
    if n < 0:
        return 0
    return n

In [101]:
noneg(7)

7

In [102]:
noneg(-3)

0

In [107]:
noneg(v)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [108]:
@np.vectorize
def noneg(n):
    if n < 0:
        return 0
    return n


In [109]:
def noneg(n):
    if n < 0:
        return 0
    return n

noneg = np.vectorize(noneg)

In [110]:
noneg(3)

array(3)

In [111]:
noneg(v)

array([0, 0, 0, 0, 1, 2])

In [112]:
nv = np.array([-1,np.nan,1])
np.sin(nv)

array([-0.84147098,         nan,  0.84147098])

In [113]:
#NaN 
noneg(nv)

C:\Users\imran\anaconda3\lib\site-packages\numpy\lib\function_base.py:2192: RuntimeWarning: invalid value encountered in ? (vectorized)
  outputs = ufunc(*inputs)


ValueError: cannot convert float NaN to integer

In [114]:
np.nan >0

False

In [115]:
np.nan < 0

False

In [117]:
np.nan == np.nan

False

In [118]:
@np.vectorize
def noneg(n):
    if not np.isnan(n) and n < 0:
        return n.__class__(0)
    return n


In [119]:
noneg(nv)

array([ 0., nan,  1.])

In [120]:
@np.vectorize
def isneg(n):
    return not np.isnan(n) and n < 0

In [122]:
nv[isneg(nv)] = 0

In [123]:
nv

array([ 0., nan,  1.])

In [127]:
np.base_repr(-5, base=2)

'-101'